services:
  chatbot-service:
    image: chatbot-service:1.0
    build:
      context: ./chatbot-service
    ports:
      - "8090:8090"
  sugerencias-service:
    image: sugerencia-service:1.0
    build:
      context: ./sugerencias-service
    ports:
      - "8091:8091"
  nlp-service:
    image: nlp-service:1.0
    build:
      context: ./nlp-service
    ports:
      - "8093:8093"
  eureka-server:
    image: eureka-server:1.0
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
networks:
  micro-net:
    driver: bridge
