server:
  port: 8093
eureka:
  instance:
    prefer-ip-address: true
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
spring:
  application:
    name: nlp-service
  config:
    import: optional:configserver:http://localhost:8888
