<<<<<<< HEAD
<<<<<<< HEAD
=======
server:
  port: 4000

>>>>>>> rescate-nlp
spring:
  application:
    name: gateway

  config:
    import: "optional:configserver:http://config:8888"
<<<<<<< HEAD

  cloud:
    config:
      uri: http://config:8888
      fail-fast: false
      username: user
      password: ${CONFIG_SERVICE_PASSWORD}

=======
    password: ${CONFIG_SERVICE_PASSWORD}

  management:
    endpoints:
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always
      info:
        enabled: true  # 👈 Activación manual
      gateway:
        enabled: true  # 👈

  cloud:
    gateway:
      routes:
        - id: chatbot-service
          uri: lb://chatbot-service
          predicates:
            - Path=/api/chatbot/**
          filters:
            - StripPrefix=2
>>>>>>> rescate-nlp
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
<<<<<<< HEAD
    registerWithEureka: true
    fetchRegistry: true
=======
    registerWithEureka: true  # Asegúrate de que esté en true
    fetchRegistry: true       # Para descubrir otros servicios
    enabled: true             # Habilita el cliente Eureka
  instance:
    appName: gateway          # Nombre claro para el registro
    preferIpAddress: true     # Usa IP en lugar de hostname (útil en Docker)
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
>>>>>>> rescate-nlp
=======
spring:
  application:
    name: gateway

  config:
    import: "optional:configserver:http://config:8888"

  cloud:
    config:
      uri: http://config:8888
      fail-fast: false
      username: user
      password: ${CONFIG_SERVICE_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
>>>>>>> 846f88161ea4aaf513941fd9b73c382eacd7b663
