<<<<<<< HEAD
eureka:
  instance:
    hostname: eureka-server  # ← Nombre que quieres usar
    preferIpAddress: false   # ← Importante desactivar esto
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/  # ← Usa el mismo nombre aquíureka:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
=======
eureka:
  instance:
    hostname: eureka-server  # ← Nombre que quieres usar
    preferIpAddress: false   # ← Importante desactivar esto
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/  # ← Usa el mismo nombre aquíureka:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
>>>>>>> 846f88161ea4aaf513941fd9b73c382eacd7b663
